### ISSUE TITLE
Invalidations are no longer working in v1.0.1 if URL has encodeable characters

### ISSUE THREAD

**Issue by dkrylovsb** [apancutt/deploy-aws-s3-cloudfront#7]
Invalidations have stopped working (at least for us) in v1.0.1 due to [this change](https://github.com/apancutt/deploy-aws-s3-cloudfront/commit/fe900ba7a06df0fdf6976ae07cb04331b50c65b4). URLs such as \* are now being encoded and passed to AWS as \%2A, which throws CloudFront off. It does not return an error, but invalidations aren't happening either.

**Comment by apancutt** [comment]
Thanks for raising this issue. It has been fixed in 1.0.2.

NB: Invalidation paths provided via command options are no longer encoded automatically and must therefore be provided in an encoded format (i.e. you don't need to change anything but CloudFront should now interpret `*` as a wildcard correctly again.

**Comment by dkrylovsb** [comment]
👍
